[build]
  publish = "public"
  command = "npm install"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/create-payment-intent"
  to = "/.netlify/functions/create-payment-intent"
  status = 200
  force = true